apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sudoku
spec:
  project: default
  source:
    repoURL: 'https://github.com/glroland/sudoku.git'
    path: deploy/helm/sudoku
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sudoku
